version : '3'

networks:
  default:
    external:
      name: elfstore-network

services :
  edge1:
    image: elfstore
    volumes:
      - ./Logs/:/edgefs/logs/
    networks:
      default:
        ipv4_address: 174.10.10.0
    expose:
      - "7000"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 1 174.10.10.0 7000 85 174.10.0.2 9090  /edgefs/data  /edgefs/logs

  edge2:
    image: elfstore
    volumes:
      - ./Logs/:/edgefs/logs/
    networks:
      default:
        ipv4_address: 174.10.10.1
    expose:
      - "7001"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 2 174.10.10.1 7001 85 174.10.0.2 9090  /edgefs/data  /edgefs/logs

  edge3:
    image: elfstore
    networks:
      default:
        ipv4_address: 174.10.10.2
    expose:
      - "7002"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 3 174.10.10.2 7002 85 174.10.0.3 9091  /edgefs/data  /edgefs/logs

  edge4:
    image: elfstore
    volumes:
      - ./Logs/:/edgefs/logs/
    networks:
      default:
        ipv4_address: 174.10.10.3
    expose:
      - "7003"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 4 174.10.10.3 7003 85 174.10.0.3 9091  /edgefs/data /edgefs/logs

  edge5:
    image: elfstore
    volumes:
      - ./Logs/:/edgefs/logs/
    networks:
      default:
        ipv4_address: 174.10.10.4
    expose:
      - "7004"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 5 174.10.10.4 7004 85 174.10.0.4 9092  /edgefs/data /edgefs/logs

  edge6:
    image: elfstore
    volumes:
      - ./Logs/:/edgefs/logs/
    networks:
      default:
        ipv4_address: 174.10.10.5
    expose:
      - "7005"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 6 174.10.10.5 7005 85 174.10.0.4 9092  /edgefs/data /edgefs/logs

  edge7:
    image: elfstore
    volumes:
      - ./Logs/:/edgefs/logs/
    networks:
      default:
        ipv4_address: 174.10.10.6
    expose:
      - "7006"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 7 174.10.10.6 7006 85 174.10.0.5 9093  /edgefs/data /edgefs/logs

  edge8:
    image: elfstore
    volumes:
      - ./Logs/:/edgefs/logs/
    networks:
      default:
        ipv4_address: 174.10.10.7
    expose:
      - "7007"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.edge.server.EdgeServer 8 174.10.10.7 7007 85 174.10.0.5 9093  /edgefs/data /edgefs/logs
