version : '3'

networks:
  default:
    external:
      name: elfstore-network

services :
  fog1:
    image: elfstore
    networks:
      default:
        ipv4_address: 174.10.0.2
    expose:
      - "9090"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.controlplane.FogServer 174.10.0.2 9090 1 1 0.25 0

  fog2:
    image: elfstore
    networks:
      default:
        ipv4_address: 174.10.0.3
    expose:
      - "9091"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.controlplane.FogServer 174.10.0.3 9091 1 2 0.25 0

  fog3:
    image: elfstore
    networks:
      default:
        ipv4_address: 174.10.0.4
    expose:
      - "9092"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.controlplane.FogServer 174.10.0.4 9092 2 3 0.25 0

  fog4:
    image: elfstore
    networks:
      default:
        ipv4_address: 174.10.0.5
    expose:
      - "9093"
    command: java -cp edgefs/cli/target/edgefilesystem-0.1-jar-with-dependencies.jar com.dreamlab.edgefs.controlplane.FogServer 174.10.0.5 9093 2 4 0.25 0
