/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dreamlab.edgefs.thrift;


public enum ReplicaCount implements org.apache.thrift.TEnum {
  NONE(0),
  ONE(1),
  ALL(2);

  private final int value;

  private ReplicaCount(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ReplicaCount findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return ONE;
      case 2:
        return ALL;
      default:
        return null;
    }
  }
}
