/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dreamlab.edgefs.thrift;


/**
 * The metadata of a micro-batch which is sent before a write to Fog *
 */
public enum WritePreference implements org.apache.thrift.TEnum {
  HHL(0),
  HLH(1),
  HHH(2),
  HLL(3),
  LHL(4),
  LLH(5),
  LHH(6),
  LLL(7);

  private final int value;

  private WritePreference(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static WritePreference findByValue(int value) { 
    switch (value) {
      case 0:
        return HHL;
      case 1:
        return HLH;
      case 2:
        return HHH;
      case 3:
        return HLL;
      case 4:
        return LHL;
      case 5:
        return LLH;
      case 6:
        return LHH;
      case 7:
        return LLL;
      default:
        return null;
    }
  }
}
